# -*- coding: utf-8 -*-
"""FELICIDARIO_FINAL_PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-DPOoRA743B7NiWHW7YvP8dwPfC0YVTe
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd
import pdb
import folium

import warnings
warnings.filterwarnings('ignore')

# Read and Process GeoJSON data
# If you are familiar with with Pandas, the transition will be easy

gdf = gpd.read_file('https://raw.githubusercontent.com/renatomaaliw3/public_files/master/Data%20Sets/GeoData/gadm41_PHL_2.json')
gdf.to_csv('data.csv')

# Calculate centroids
gdf['centroid_x'] = gdf['geometry'].centroid.x
gdf['centroid_y'] = gdf['geometry'].centroid.y

gdf

fig, ax = plt.subplots(figsize=(25, 25))

# Assuming 'gdf' is your GeoDataFrame
gdf.plot(ax = ax, color = 'green', edgecolor = 'black')

ax.set_title("", pad = 40, fontweight = 'bold', fontsize = 18)

# Add grid
# ax.grid(alpha = 0.5)

# Remove x and y ticks
ax.set_xticks([])
ax.set_yticks([])

# Here is a simple approach to add text (x, y, 'text')
ax.text(0.50, 0.96, 'PHILIPPINE MAP', transform = ax.transAxes, fontsize=34, fontweight='bold',
        ha='center', va='center', color='black')

plt.show()

# Isolate Quezon Province Only

gdf_manila = gdf.query("NAME_1 == 'MetropolitanManila'")
gdf_manila

# Reverse dictionary structure: value becomes key, key becomes value
replacements_reversed = {
    'Mandaluyong': 'MANDALUYONG CITY',
    'Valenzuela': 'VALENZUELA CITY',
    'MakatiCity': 'MAKATI CITY',
    'PasigCity': 'PASIG CITY',
    'QuezonCity': 'QUEZON CITY',
    'Taguig': 'TAGUIG CITY',
    'LasPiñas': 'LAS PIÑAS CITY',
    'Muntinlupa': 'MUNTINLUPA CITY',
    'Parañaque': 'PARAÑAQUE CITY',
    'PasayCity': 'PASAY CITY',
    'Marikina': 'MARIKINA CITY',
    'Malabon': 'MALABON CITY',
    'Navotas': 'NAVOTAS CITY',
    'SanJuan': 'SAN JUAN',
    'Manila': 'MANILA CITY',
    'KalookanCity': 'CALOOCAN CITY',
    'Pateros': 'PATEROS',
}

# Apply replacements to the 'NAME_2' column
gdf['NAME_2'] = gdf['NAME_2'].replace(replacements_reversed)

# Filter for municipalities and cities in Metro Manila
gdf_manila = gdf[gdf['NAME_2'].isin(replacements_reversed.values())]

# Isolate Quezon Province Only

gdf_manila = gdf.query("NAME_1 == 'MetropolitanManila'")
gdf_manila

# Basic Plotting

# Create a plot with a custom figure size of 10 inches wide by 8 inches tall
fig, ax = plt.subplots(figsize=(25, 25))

gdf_manila.plot(ax = ax, color = 'green', edgecolor = 'black')

# Add a title
ax.set_title("MetropolitanManila", pad = 10, fontweight = 'bold', fontsize = 20)

# Remove Ticks
ax.set_xticks([])
ax.set_yticks([])

plt.show()

# Basic Plotting

# Create a plot with a custom figure size of 10 inches wide by 8 inches tall
fig, ax = plt.subplots(figsize=(25, 25))

gdf_manila.plot(ax = ax, color = 'green', edgecolor = 'black')

# Add a title
ax.set_title("MetropolitanManila", pad = 20, fontweight = 'bold', fontsize = 20)

# Remove Ticks
ax.set_xticks([])
ax.set_yticks([])

# Annotate with municipality names
for x, y, label in zip(gdf_manila.centroid_x, gdf_manila.centroid_y, gdf_manila.NAME_2):
    ax.annotate(label, xy=(x, y), xytext=(3, 3), textcoords="offset points", ha = 'center', va = 'center', fontsize=10)

plt.show()

# Assuming gdf_manila is your GeoDataFrame
fig, ax = plt.subplots(figsize=(25, 25))

# Plot with distinct colors
gdf_manila.plot(
    ax=ax,
    column='NAME_2',  # Different colors based on this column
    cmap='YlGnBu',     # Or a custom colormap if needed
    legend=True,
    edgecolor='black'
)

# Add title
ax.set_title("Municipalities in Metropolitan Manila", pad=20, fontweight='bold', fontsize=18, color='black')

# Remove Ticks
ax.set_xticks([])
ax.set_yticks([])

# Annotate with municipality names
for x, y, label in zip(gdf_manila.centroid_x, gdf_manila.centroid_y, gdf_manila.NAME_2):
    ax.annotate(
        label,
        xy=(x, y),
        xytext=(3, 3),
        textcoords="offset points",
        ha='center',
        va='center',
        fontsize=10,
        color='black',
        bbox=dict(boxstyle="round,pad=0.3", edgecolor="gray", facecolor="white", alpha=0.8)
    )

plt.show()

# Add Information from External Data Source

#Importing Dataset
data = pd.read_csv('https://raw.githubusercontent.com/zai-f/zai-f/refs/heads/main/bfp.csv')
data

# Create the city_to_region_map (if not already defined)
city_to_region_map = {
    'CALOOKANCITY': 'NCR',
    'LAS PIÑAS CITY': 'NCR',
    'MAKATI CITY': 'NCR',
    'MALABON': 'NCR',
    'MANDALUYONG': 'NCR',
    'MANILA': 'NCR',
    'MARIKINA': 'NCR',
    'MUNTINLUPA': 'NCR',
    'NAVOTAS': 'NCR',
    'PARAÑAQUE CITY': 'NCR',
    'PASAY CITY': 'NCR',
    'PASIG CITY': 'NCR',
    'PATEROS': 'NCR',
    'QUEZON CITY': 'NCR',
    'SANJUAN': 'NCR',
    'TAGUIG': 'NCR',
    'VALENZUELA': 'NCR'
}
# Merge the data
merged_data = gdf_manila.merge(data, left_on='NAME_2', right_on='CITY_MUNICIPALITY', how='inner')

columns_to_drop = ['GID_0', 'GID_2', 'NL_NAME_1', 'NL_NAME_2', 'VARNAME_2', 'TYPE_2', 'ENGTYPE_2', 'CC_2', 'HASC_2', 'REGION_y']  # Replace 'REGION_x' with the correct name 'REGION_y'
merged_data = merged_data.drop(columns=columns_to_drop, errors='ignore') #errors='ignore' will ignore errors if any column in columns_to_drop list does not exist, instead of raising a KeyError.

# Convert to DataFrame
final_data = pd.DataFrame(merged_data)  # Convert to DataFrame
final_data = final_data.drop(columns=['geometry'])  # Remove geometry column

# Display the DataFrame
final_data

# Display specific columns from the final_data DataFrame
columns_to_display = ['CITY_MUNICIPALITY', 'YEAR', 'INCIDENTS', 'INJURIES', 'DEATHS', 'ESTIMATED_DAMAGES']
display(final_data[columns_to_display])

# Filter data for years 2016 to 2021
filtered_data = final_data[(final_data['YEAR'] >= 2016) & (final_data['YEAR'] <= 2021)]

# Group by city and year, and sum the relevant columns
city_tally = filtered_data.groupby(['CITY_MUNICIPALITY', 'YEAR']).agg(
    {'INCIDENTS': 'sum', 'INJURIES': 'sum', 'DEATHS': 'sum', 'ESTIMATED_DAMAGES': 'sum'}
).reset_index()

# Display the city tally
city_tally

# Compare cities to determine which ones have the highest incidents, injuries, deaths, and damages. This could be used to prioritize resources and safety measures for cities with higher numbers. put in data frame

# Assuming 'final_data' DataFrame from the previous code is available

# Display specific columns for comparison
comparison_columns = ['CITY_MUNICIPALITY', 'INCIDENTS', 'INJURIES', 'DEATHS']
comparison_df = final_data[comparison_columns].copy()  # Create a copy to avoid SettingWithCopyWarning

# Convert relevant columns to numeric, coercing errors to NaN
for col in ['INCIDENTS', 'INJURIES', 'DEATHS']:
    comparison_df[col] = pd.to_numeric(comparison_df[col], errors='coerce')

# Group data by city and sum the relevant columns
city_comparison = comparison_df.groupby('CITY_MUNICIPALITY').sum()

# Sort by incidents in descending order
city_comparison = city_comparison.sort_values('INCIDENTS', ascending=False)
city_comparison = city_comparison.sort_values('INJURIES', ascending=False)
city_comparison = city_comparison.sort_values('DEATHS', ascending=False)

# Display the comparison DataFrame
city_comparison

# Assuming 'final_data' DataFrame from the previous code is available

# Group data by city and year, and sum the relevant columns
yearly_city_tally = final_data.groupby(['CITY_MUNICIPALITY', 'YEAR']).agg(
    {'INCIDENTS': 'sum', 'INJURIES': 'sum', 'DEATHS': 'sum', 'ESTIMATED_DAMAGES': 'sum'}
).reset_index()

# Display the yearly city tally
yearly_city_tally

import matplotlib.pyplot as plt
import math

# Get unique years
years = yearly_city_tally['YEAR'].unique()

n_cols = 1  # For a less crowded layout, we can plot one year per figure
n_rows = len(years)  # One plot per row

# Create a new figure for each year to avoid crowding
for i, year in enumerate(years):
    fig, ax = plt.subplots(figsize=(12, 8))  # Make the figure large enough for better readability

    # Filter data for the current year
    yearly_data = yearly_city_tally[yearly_city_tally['YEAR'] == year]

    # Create a bar plot for the current year
    bars = ax.bar(yearly_data['CITY_MUNICIPALITY'], yearly_data['INCIDENTS'])
    ax.set_xlabel("City Municipality", fontsize=12)
    ax.set_ylabel("Number of Incidents", fontsize=12)
    ax.tick_params(axis='x', rotation=45)  # Rotate x-axis labels for readability

    # Add value labels above each bar
    for bar in bars:
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width() / 2,  # X-coordinate: center of the bar
            height,  # Y-coordinate: top of the bar
            f"{int(height)}",  # Convert height to an integer string
            ha="center",  # Horizontal alignment
            va="bottom",   # Vertical alignment
            fontsize=10
        )

    # Remove grid lines for a cleaner look
    ax.grid(False)

    # Add a thicker border around the plot
    for spine in ax.spines.values():
        spine.set_edgecolor('black')  # Set border color to black
        spine.set_linewidth(3)  # Set border thickness to 3 (or adjust as needed)

    # Adjust the layout to make sure there’s enough space
    plt.tight_layout(pad=5.0)

    # Add a suptitle for the entire figure
    plt.suptitle(f"Incident Distribution by City Municipality in {year}", fontsize=18, fontweight='bold')

    # Show the plot for the current year
    plt.show()

import matplotlib.pyplot as plt
import math

# Get unique years
years = yearly_city_tally['YEAR'].unique()

# Create a new figure for each year to avoid crowding
for i, year in enumerate(years):
    fig, ax = plt.subplots(figsize=(12, 8))  # Make the figure large enough for better readability

    # Filter data for the current year
    yearly_data = yearly_city_tally[yearly_city_tally['YEAR'] == year]

    # Create a bar plot for the current year
    bars = ax.bar(yearly_data['CITY_MUNICIPALITY'], yearly_data['INJURIES'])
    ax.set_xlabel("City Municipality", fontsize=12)
    ax.set_ylabel("Number of Injuries", fontsize=12)
    ax.tick_params(axis='x', rotation=45)  # Rotate x-axis labels for readability

    # Add value labels above each bar
    for bar in bars:
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width() / 2,  # X-coordinate: center of the bar
            height,  # Y-coordinate: top of the bar
            f"{int(height)}",  # Convert height to an integer string
            ha="center",  # Horizontal alignment
            va="bottom",   # Vertical alignment
            fontsize=10
        )

    # Remove grid lines for a cleaner look
    ax.grid(False)

    # Add a thicker border around the plot
    for spine in ax.spines.values():
        spine.set_edgecolor('black')  # Set border color to black
        spine.set_linewidth(3)  # Set border thickness to 3 (or adjust as needed)

    # Adjust the layout to make sure there’s enough space
    plt.tight_layout(pad=5.0)

    # Add a suptitle for the entire figure
    plt.suptitle(f"Incident Distribution by City Municipality in {year}", fontsize=18, fontweight='bold')

    # Show the plot for the current year
    plt.show()

import matplotlib.pyplot as plt
import math

# Get unique years
years = yearly_city_tally['YEAR'].unique()

# Create a new figure for each year to avoid crowding
for i, year in enumerate(years):
    fig, ax = plt.subplots(figsize=(12, 8))  # Make the figure large enough for better readability

    # Filter data for the current year
    yearly_data = yearly_city_tally[yearly_city_tally['YEAR'] == year]

    # Create a bar plot for the current year
    bars = ax.bar(yearly_data['CITY_MUNICIPALITY'], yearly_data['DEATHS'])
    ax.set_xlabel("City Municipality", fontsize=12)
    ax.set_ylabel("Number of Deaths", fontsize=12)
    ax.tick_params(axis='x', rotation=45)  # Rotate x-axis labels for readability

    # Add value labels above each bar
    for bar in bars:
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width() / 2,  # X-coordinate: center of the bar
            height,  # Y-coordinate: top of the bar
            f"{int(height)}",  # Convert height to an integer string
            ha="center",  # Horizontal alignment
            va="bottom",   # Vertical alignment
            fontsize=10
        )

    # Remove grid lines for a cleaner look
    ax.grid(False)

    # Add a thicker border around the plot
    for spine in ax.spines.values():
        spine.set_edgecolor('black')  # Set border color to black
        spine.set_linewidth(3)  # Set border thickness to 3 (or adjust as needed)

    # Adjust the layout to make sure there’s enough space
    plt.tight_layout(pad=5.0)

    # Add a suptitle for the entire figure
    plt.suptitle(f"Deaths Distribution by City Municipality in {year}", fontsize=18, fontweight='bold')

    # Show the plot for the current year
    plt.show()

# Group data by city and sum incidents
incident_counts = yearly_city_tally.groupby('CITY_MUNICIPALITY')['INCIDENTS'].sum()

# Print the incident counts for each municipality
incident_counts

import matplotlib.pyplot as plt

# Calculate incident counts per municipality
incident_counts = final_data.groupby('NAME_2')['INCIDENTS'].sum().fillna(0)

# Merge incident counts with GeoDataFrame
merged_gdf = gdf_manila.merge(incident_counts, left_on='NAME_2', right_index=True, how='left').fillna(0)

# Create the plot
fig, ax = plt.subplots(figsize=(25, 25))

# Plot the map with color based on incident counts
merged_gdf.plot(
    column='INCIDENTS',
    cmap='YlOrRd',
    linewidth=0.8,
    ax=ax,
    edgecolor='black',
    legend=True,
    missing_kwds={'color': 'lightgrey'}
)

# Add municipality names and incident counts
for x, y, name, incidents in zip(
    merged_gdf.centroid_x,
    merged_gdf.centroid_y,
    merged_gdf.NAME_2,
    merged_gdf.INCIDENTS
):
    ax.annotate(f'{name}\n{int(incidents)}', xy=(x, y), xytext=(3, 3),
                textcoords="offset points", ha='center', va='center',
                fontsize=8, color='black', bbox=dict(boxstyle="round,pad=0.3",
                                                     edgecolor='black',
                                                     facecolor='white',
                                                     alpha=0.7))

# Customize the plot
ax.set_title('Fire Incidents in Metropolitan Manila', fontsize=20)
ax.set_axis_off()

# Show the plot
plt.show()

# Group data by city and sum deaths
death_counts = final_data.groupby('CITY_MUNICIPALITY')['DEATHS'].sum()

# Print the death counts for each municipality
death_counts

# Calculate death counts per municipality
death_counts = final_data.groupby('CITY_MUNICIPALITY')['DEATHS'].sum().fillna(0)

# Merge death counts with GeoDataFrame
merged_gdf = gdf_manila.merge(death_counts, left_on='NAME_2', right_index=True, how='left').fillna(0)

# Create the plot
fig, ax = plt.subplots(figsize=(25, 25))

# Plot the map with color based on death counts
merged_gdf.plot(
    column='DEATHS',
    cmap='YlOrRd',
    linewidth=0.8,
    ax=ax,
    edgecolor='black',
    legend=True,
    missing_kwds={'color': 'lightgrey'}
)

# Add municipality names and death counts
for x, y, name, deaths in zip(
    merged_gdf.centroid_x,
    merged_gdf.centroid_y,
    merged_gdf.NAME_2,
    merged_gdf.DEATHS
):
    ax.annotate(f'{name}\n{int(deaths)}', xy=(x, y), xytext=(3, 3),
                textcoords="offset points", ha='center', va='center',
                fontsize=8, color='black', bbox=dict(boxstyle="round,pad=0.3",
                                                     edgecolor='black',
                                                     facecolor='white',
                                                     alpha=0.7))

# Customize the plot
ax.set_title('Fire Deaths in Metropolitan Manila', fontsize=20)
ax.set_axis_off()

# Show the plot
plt.show()

# Group data by city and sum injuries
injury_counts = final_data.groupby('CITY_MUNICIPALITY')['INJURIES'].sum()

# Print the injury counts for each municipality
injury_counts

# Group data by city and sum injuries
injury_counts = final_data.groupby('CITY_MUNICIPALITY')['INJURIES'].sum().fillna(0)

# Merge injury counts with GeoDataFrame
merged_gdf = gdf_manila.merge(injury_counts, left_on='NAME_2', right_index=True, how='left').fillna(0)

# Create the plot
fig, ax = plt.subplots(figsize=(25, 25))

# Plot the map with color based on injury counts
merged_gdf.plot(
    column='INJURIES',
    cmap='YlOrRd',
    linewidth=0.8,
    ax=ax,
    edgecolor='black',
    legend=True,
    missing_kwds={'color': 'lightgrey'}
)

# Add municipality names and injury counts
for x, y, name, injuries in zip(
    merged_gdf.centroid_x,
    merged_gdf.centroid_y,
    merged_gdf.NAME_2,
    merged_gdf.INJURIES
):
    ax.annotate(f'{name}\n{int(injuries)}', xy=(x, y), xytext=(3, 3),
                textcoords="offset points", ha='center', va='center',
                fontsize=8, color='black', bbox=dict(boxstyle="round,pad=0.3",
                                                     edgecolor='black',
                                                     facecolor='white',
                                                     alpha=0.7))

# Customize the plot
ax.set_title('Fire Injuries in Metropolitan Manila', fontsize=20)
ax.set_axis_off()

# Show the plot
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming 'city_comparison' DataFrame from the previous code is available

# Set Seaborn style
sns.set_theme(style="whitegrid")

# Create the bar plot
plt.figure(figsize=(12, 6))  # Adjust figure size for better readability
ax = sns.barplot(x=city_comparison.index, y='INCIDENTS', data=city_comparison, palette="viridis")

# Customize the plot
plt.xlabel("City/Municipality", fontsize=12)
plt.ylabel("Total Incidents (2012-2016)", fontsize=12)  # Updated y-axis label
plt.title("Total Fire Incidents per City/Municipality in Metro Manila (2012-2016)", fontsize=14, fontweight='bold')  # Updated title
plt.xticks(rotation=45, ha="right")  # Rotate x-axis labels for better visibility
plt.tight_layout()  # Adjust layout to prevent labels from overlapping

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.0f'),  # Format to integer
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center',
                xytext=(0, 9),  # Adjust vertical offset
                textcoords='offset points',
                fontsize=9)

# Show the plot
plt.show()

# ---Additional Graphs---
#1. Injuries per City
plt.figure(figsize=(12, 6))
ax = sns.barplot(x=city_comparison.index, y='INJURIES', data=city_comparison, palette='magma')
plt.xlabel("City/Municipality", fontsize=12)
plt.ylabel("Total Injuries (2012-2016)", fontsize=12)
plt.title("Total Injuries per City/Municipality in Metro Manila (2012-2021)", fontsize=14, fontweight='bold')
plt.xticks(rotation=45, ha="right")
plt.tight_layout()

for p in ax.patches:
    ax.annotate(format(p.get_height(), '.0f'), (p.get_x() + p.get_width() / 2., p.get_height()), ha='center', va='center', xytext=(0, 9), textcoords='offset points', fontsize=9)

plt.show()

#2. Deaths per City
plt.figure(figsize=(12, 6))
ax = sns.barplot(x=city_comparison.index, y='DEATHS', data=city_comparison, palette='rocket')
plt.xlabel("City/Municipality", fontsize=12)
plt.ylabel("Total Deaths (2012-2016)", fontsize=12)
plt.title("Total Deaths per City/Municipality in Metro Manila (2012-2016)", fontsize=14, fontweight='bold')
plt.xticks(rotation=45, ha="right")
plt.tight_layout()

for p in ax.patches:
    ax.annotate(format(p.get_height(), '.0f'), (p.get_x() + p.get_width() / 2., p.get_height()), ha='center', va='center', xytext=(0, 9), textcoords='offset points', fontsize=9)

plt.show()

# Select numerical features for descriptive statistics
numerical_features = ['INCIDENTS', 'INJURIES', 'DEATHS']

# Calculate descriptive statistics
descriptive_stats = final_data[numerical_features].describe()

# Display the descriptive statistics
descriptive_stats

# Select numerical features for descriptive statistics
numerical_features = ['INCIDENTS', 'INJURIES', 'DEATHS']

# Calculate descriptive statistics
descriptive_stats = final_data[numerical_features].describe()

# Display the descriptive statistics
descriptive_stats

# --- Plotting the descriptive statistics ---

import matplotlib.pyplot as plt
import seaborn as sns

# Set the style for better visualization
sns.set_style("whitegrid")

# Create the figure and axes for the subplots
fig, axes = plt.subplots(nrows=len(numerical_features), ncols=1, figsize=(10, 12))

# Iterate over each numerical feature to create individual plots
for i, feature in enumerate(numerical_features):
    ax = axes[i]  # Select the current axis

    # Plot the distribution
    sns.histplot(final_data[feature], kde=True, ax=ax, color='skyblue', edgecolor='black', linewidth=0.5)

    # Add descriptive statistics as text on the plot
    stats = descriptive_stats[feature]
    textstr = '\n'.join((
        f'Mean: {stats["mean"]:.2f}',
        f'Median: {stats["50%"]:.2f}',
        f'Std Dev: {stats["std"]:.2f}',
        f'Min: {stats["min"]:.2f}',
        f'Max: {stats["max"]:.2f}'
    ))
    props = dict(boxstyle='round', facecolor='wheat', alpha=0.5)
    ax.text(0.05, 0.95, textstr, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)


    # Set labels and title
    ax.set_title(f'Distribution of {feature}', fontsize=14)
    ax.set_xlabel(feature, fontsize=12)
    ax.set_ylabel('Frequency', fontsize=12)

# Adjust layout for better spacing
plt.tight_layout()

# Display the plot
plt.show()

import folium
import pandas as pd

# Create a base map centered on Metro Manila
m = folium.Map(location=[14.5995, 120.9842], zoom_start=10)

# Define a list of colors for the markers
colors = ['red', 'blue', 'green', 'purple', 'orange', 'darkred', 'lightred', 'beige', 'darkblue', 'darkgreen', 'cadetblue', 'darkpurple', 'black', 'pink', 'lightblue', 'lightgreen', 'gray', 'black', 'lightgray']

# Merge city_comparison data with GeoDataFrame
merged_data = gdf_manila.merge(city_comparison, left_on='NAME_2', right_index=True, how='left')

# Create choropleth map
folium.Choropleth(
    geo_data=merged_data,
    name="choropleth",
    data=merged_data,
    columns=["NAME_2", "INCIDENTS"],
    key_on="feature.properties.NAME_2",
    fill_color="YlOrRd",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Total Incidents (2012-2016)"
).add_to(m)

# Add markers for each city with incident information and varying colors
for i, (city, row) in enumerate(city_comparison.iterrows()):
    # Find the corresponding row in final_data based on the city name
    city_data = final_data[final_data['NAME_2'] == city].iloc[0]  # Assuming unique city names
    latitude = city_data['centroid_y']
    longitude = city_data['centroid_x']
    incidents = int(row['INCIDENTS'])
    injuries = int(row['INJURIES'])
    deaths = int(row['DEATHS'])
    popup_text = f"<b>City:</b> {city}<br><b>Incidents:</b> {incidents}<br><b>Injuries:</b> {injuries}<br><b>Deaths:</b> {deaths}"

    # Cycle through the colors list
    color_index = i % len(colors)
    folium.Marker(
        location=[latitude, longitude],
        popup=popup_text,
        tooltip=city,
        icon=folium.Icon(color=colors[color_index], icon='info-sign')
    ).add_to(m)

# Display the map
m

# save the foluim in html

m.save('fire_incidents_map.html')