# -*- coding: utf-8 -*-
"""MIDTERM ACTIVITY#1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cAUl7rsdo3uxPf19bMigSrZUjRW7eVJ8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#ACTIVITY 1
# 1. Create a Figure with a single Axes
# 2. Plot a line graph on the Axes using random values

fig, ax = plt.subplots()
ax.plot(np.random.rand(10))
plt.show()

#ACTIVITY 2
# 1. Create a line graphn with custom labels and title
# 2. Experiment with line style and color (e.g., dashed lines, red color)

x= [10,20,30,40,50]
y= [10,20,30,40,50]
plt.plot(x,y, marker='o',linestyle='-', color='blue')
plt.title('Line Graph')
plt.xlabel('Horizontal-axis')
plt.ylabel('Vertical-axis')
plt.grid(True)
plt.show()

# ACTIVITY 3.
# 1. Create a bar graph with custom colors for each bar.
# 2. Add labels and grid lines to imporve readability.

x = ["RED","GREEN","BLUE","YELLOW","ORANGE","PINK"]
y = [30,30,50,20,10,40]
colors = ['red', 'green', 'blue', 'yellow', 'orange','pink']
plt.bar(x,y, color=colors)
plt.xlabel('Color-Axis')
plt.ylabel('Number-Axis')
plt.title('Bar Graph')
plt.grid(True)
plt.show()

# ACTIVITY 4
# 1. Use subplots to create a figure with two rows and one column.
# 2. Add a line graph in the first row and a bar graph in the second row.

x2 = ["RED","GREEN","BLUE","YELLOW","ORANGE","PINK"]
y2 = [30,30,50,20,10,40]
colors = ['red', 'green', 'blue', 'yellow', 'orange','pink']
fig, axs = plt.subplots(2,1,figsize=(6,6))
fig.suptitle('Line Graph and Bar Graph')
axs[0].plot(x2,y2,marker='o',linestyle='dashed', color='blue', label='Line Graph')
axs[0].set_title('Line Graph')
axs[1].bar(x2,y2,color=colors, label = 'Bar Graph')
axs[1].set_title('Bar Graph')
plt.tight_layout()
plt.show()

#ACTIVITY 5
# 1. Add a legend and grid to a line or bar graph
# 2. Annotate the highest point in your graph

x2 = ["RED","GREEN","BLUE","YELLOW","ORANGE","PINK"]
y2 = [30,30,50,20,10,40]
colors = ['red', 'green', 'blue', 'yellow', 'orange','pink']

fig, axs = plt.subplots(figsize=(10,4))

axs.bar(x2,y2,color=colors, label = 'Bar Graph')
axs.legend(title='Color Preference', labels=x2)
axs.grid(True)

max_index = np.argmax(y2)
max_value = y2[max_index]

plt.annotate(f'FAVORITE COLOR: ({x2[max_index]}, {max_value})', xy=(x2[max_index], max_value), xytext=(50, -10), textcoords='offset points', arrowprops=dict(arrowstyle='->', connectionstyle='arc3,rad=.1'))

plt.title('Enhanced Bar Graph with Legend and Grid')
plt.xlabel('Color')
plt.tight_layout()
plt.show()

"""DISCUSSION QUESTIONS:

1. When would you choose a bar graph over a line graph, and why?

  I preffered to choose a bar graph over a line graph when comparing separate categories, like favorite colors or types of pets, to easily see which category has the most or least and to highlight the differences between them.

2. What are some advantages of using subplots in a single figure?

  Subplots allows us to compare and contrast different datasets or the views of the same data within a single figure, and most importantly is by enhancing the data visualization and understanding. They also improve the organization and readability of my analysis, making it easier to identify patterns and relationships across plots.

3. How does customizing graphs improve the clarity of data visualization?

  By Customizing graphs significantly enhances data visualization clarity. By using distinct colors, informative labels, and clear titles, As we highlight the key insights and improve readability. Thoughtful use of line styles, markers, and fonts makes the graph visually appealing and engaging.
  
  In addition to that customization allows us to tailor visualizations to specific audiences and purposes, ensuring effective communication. Lastly, well-crafted customizations transform data into a compelling and easily understood Data.



"""