# -*- coding: utf-8 -*-
"""ACTIVITY  #1_FELICIDARIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hvcePcyz-nFthKLJlHEx79Mh8IoNxicJ
"""

# Printing Hello, World use f-string
message = "Hello, World"
print(f"{message}")

# Integers
my_year = 2004
print(my_year)

# Floats
my_age = 20
print(my_age)

# Strings
my_name = "Zaira Felicidario"
print(my_name)

# Booleans
my_boolean = True
print(my_boolean)

# Greetings
greeting_message = "Good morning"
name = "Ma'am Susa"

print(f"{greeting_message}, {name}!")

# List
my_list = [1, 2, 3]
print("Original list:", my_list)

# Dictionary
my_dictionary = {"name": "Zaira", "age": 20}
print("Original dictionary:", my_dictionary)

# Retrieve the value associated with the key "name"
name = my_dictionary["name"]
print("Name from dictionary:", name)

# Add a new key-value pair
my_dictionary["city"] = "London"
print("Dictionary after adding a new key-value pair:", my_dictionary)

# Tuple
my_tuple = (1, 2, 3)
print("Tuple:", my_tuple)

# Set
my_set = {1, 2, 3, 3}
print("Set:", my_set)

# Add an element to the set
my_set.add(4)
print("Set after adding element:", my_set)

number = 8

if number > 5 and number < 10:
  print(f"{number} is greater than 5 and less than 10")

if number > 10 or number < 2:
  print(f"{number} is greater than 10 or less than 2")
else:
  print(f"{number} is not greater than 10 or less than 2")

if number != 5:
  print(f"{number} is not equal to 5")

# Get user input for age
user_input = input("Enter your age: ")

# Convert input to an integer
age = int(user_input)

# Evaluate age using if statements
if age < 0:
    print("Age cannot be negative.")
elif age == 0:
    print("You are a newborn.")
elif age < 13:
    print("You are a child.")
elif age < 18:
    print("You are a teenager.")
elif age < 65:
    print("You are an adult.")
else:
    print("You are a senior.")

# Iterate over a range of ages (1 to 10)
print("\nIterating over ages from 1 to 10:")
for i in range(1, 11):
    print(i)