# -*- coding: utf-8 -*-
"""Lab Activity 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUbyNB-CmFllV-1ZpP69YvO-LPzcRCMN
"""

import numpy as np
import pandas as pd
import datetime
from datetime import datetime

# Question 1
# What is the day for the date, September 11, 1952
# Use .strftime('%A') to get identify the day (e.g Monday, Tuesday)

my_year = 1952
my_month = 9
my_day = 11

my_date = datetime(my_year, my_month, my_day)
day_of_week = my_date.strftime('%A')
print(day_of_week)

# Question 2
# Using pd.date_range, create dates starting from october 15, 2008 with 85 periods with day frequency.
# What date is second to the last?

idx = pd.date_range('10/15/2008', periods=85, freq='D')
print (idx [-2])

# Load Dataset (starbucks)

starbucks = pd.read_csv('https://raw.githubusercontent.com/renatomaaliw3/public_files/refs/heads/master/Data%20Sets/starbucks.csv')
display(starbucks)

# Question No. 3
# Use the starbucks.csv dataset.
# If you resemble the 'Close' column to weekly mean frequency, what is the value of 2016-05-01

starbucks['Date'] = pd.to_datetime(starbucks['Date'])
starbucks = starbucks.set_index('Date')
print(starbucks['Close'].resample('W').mean()['2016-05-01'])

# Question No. 4
# Use the starbucks.csv dataset
# If you resample the 'Close' column to quarter end median frequecy, what is the value of 2017-12-31?

quarter_end_median = starbucks['Close'].resample('QE').median()
print(quarter_end_median['2017-12-31'])

# Question No. 5
# Use the starbucks.csv dataset.
# If you resample the 'Volume' column to semi-month end mean frequency, what is the median value of the last five dates?


semi_month_end_mean = starbucks['Volume'].resample('SME').mean()
last_five_dates_median = semi_month_end_mean.tail(5).median()
last_five_dates_median

# Question No. 6
#Create a bar graph (vertical), show the maximum 'Close' Price per month
import matplotlib.pyplot as plt

title = 'Monthly Max Closing Price for Starbucks'
starbucks['Close'].resample('ME').max().plot.bar(figsize=(16, 6), title=title, color='red')
plt.show()

# Question No.7
# If I shift forward the starbucks data by a value of 17, what is the new value of 'Close' price for 2015-02-26?

shifted_forward = starbucks['Close'].shift(17)
print(shifted_forward['2015-02-26'])

# Question No.8
# If I shift backward the starbucks data by a value of 28, what is the new value of 'Close' price for 2018-08-t31?

shifted_backward = starbucks['Close'].shift(-28)
print(shifted_backward['2018-08-31'])

# Question No.9
# Using moving average (rolling) with 14 days window, find the closing price at 2015-04-09

rolling_mean = starbucks['Close'].rolling(window=14).mean()
print(rolling_mean['2015-04-09'])

# Question No. 10
# Create the graph below with the differnt rolling windows of 7, 14, 21, 30

starbucks['Close: 7 days'] = starbucks['Close'].rolling(window=7).mean()
starbucks['Close: 14 days'] = starbucks['Close'].rolling(window=14).mean()
starbucks['Close: 21 days'] = starbucks['Close'].rolling(window=21).mean()
starbucks['Close: 30 days'] = starbucks['Close'].rolling(window=30).mean()

starbucks[['Close','Close: 7 days','Close: 14 days','Close: 21 days','Close: 30 days']].plot(figsize=(12,5)).autoscale(axis='x',tight=True);

# Question No. 11
# Based on the graph above, what is your take on increasing and decreasing the number of windows for rolling or moving average?

"""If you use more windows, the line is smoother and shows long-term trends. If you use fewer windows, the line is more sensitive to recent changes but can look noisier.

"""