# -*- coding: utf-8 -*-
"""LABORATORY 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xltoUt194CqNsPTgR3xUHctJ_ckXgDB
"""

import pandas as pd
import numpy as np
import requests
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
from bs4 import BeautifulSoup

warnings.filterwarnings("ignore")

# URL
url = f'https://www.cbssports.com/nba/standings' #

# Send requests
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

# Response
response = requests.get(url = url, headers = headers)

# Create a bs4 object to parse the HTML content
soup = BeautifulSoup(response.content, 'html.parser')

# Find the tbody containing Eastern Conference Teams, you can use select('tbody')[0], means first tbody found

tbody = soup.select('tbody')[0]

# Find all team names
team = []

for i in tbody.find_all('a'):
    text = i.get_text().strip()
    if text:
        team.append(text)

# Data for Eastern Conference Teams

data = []
for row in tbody.find_all('tr'):
    col = row.find_all('td')
    col = [ele.text.strip() for ele in col]
    data.append([ele for ele in col if ele])
data = pd.DataFrame(data, columns = ['No.', 'Team', 'W', 'L', 'PCT', 'GB', 'PPG', 'OPPG', 'DIFF', 'HOME', 'ROAD', 'DIV', 'CONF', 'STRK', 'L10', 'W', 'DIV', 'POST'])

# Construct Data Frame for Eastern Conference Teams

team_df = pd.DataFrame(team, columns = ['Team'])
team_df

# Construct Data Frame for Eastern Conference Teams

team_data = pd.DataFrame(data).iloc[:, 2:]
team_data

# Combine both Data Frame (Eastern Conference)

df_final = pd.concat([team_df, team_data], axis = 1)
df_final

# Find the table containing (Western Conference Teams), you can use select('tbody')[1], means second tbody found

tbody1 = soup.select('tbody')[1]

# Find all team names
team = []

for i in tbody1.find_all('a'):
    text = i.get_text().strip()
    if text:
        team.append(text)

# Data for Western Conference Teams

data = []
for row in tbody1.find_all('tr'):
    col = row.find_all('td')
    col = [ele.text.strip() for ele in col]
    data.append([ele for ele in col if ele])
data = pd.DataFrame(data, columns = ['No.', 'Team', 'W', 'L', 'PCT', 'GB', 'PPG', 'OPPG', 'DIFF', 'HOME', 'ROAD', 'DIV', 'CONF', 'STRK', 'L10', 'W', 'DIV', 'POST'])

# Construct Data Frame for Western Conference Teams

team_df2 = pd.DataFrame(team, columns = ['Team'])
team_df2

# Construct Data Frame for Western Conference Teams

team_data2 = pd.DataFrame(data).iloc[:, 2:]
team_data2

# Combine both Data Frame (Western Conference)

df_final2 = pd.concat([team_df2, team_data2], axis = 1)
df_final2

# Combine Eastern and Western Conference Data via pd.concat

df_combined = pd.concat([df_final, df_final2], axis = 0)
df_combined

# Sort by PCT in Descending Order

df_combined = df_combined.sort_values(by = 'PCT', ascending = False)
df_combined

# Reset Index

df_combined = df_combined.reset_index(drop = True)
df_combined